const ReaderActionTypes = {

  SET_WORD_POSITION: 'SET_WORD_POSITION',
  SET_WORD_LENGTH: 'SET_WORD_LENGTH',
  SET_WORD: 'SET_WORD',
  
  SET_CURRENT_READ_TIME: 'SET_CURRENT_READ_TIME',
  
  SET_CURRENT_TIMEOUT: 'SET_CURRENT_TIMEOUT',
  
  CHANGE_WORD_START: 'CHANGE_WORD_START',
  CHANGE_WORD_SUCCESS: 'CHANGE_WORD_SUCCESS',
  CHANGE_WORD_FAILURE: 'CHANGE_WORD_FAILURE',

  PAUSE_READING: 'PAUSE_READING',
  RESUME_READING: 'RESUME_READING',

  // ------------------------------
  SET_PART_INFO_START: 'SET_PART_INFO_START',
  SET_PART_INFO_SUCCESS: 'SET_PART_INFO_SUCCESS' 
}

export default ReaderActionTypes;