const ReaderActionTypes = {

  PAUSE_READING: 'PAUSE_READING',
  RESUME_READING: 'RESUME_READING',

  SET_PART_INFO_START: 'SET_PART_INFO_START',
  SET_PART_INFO_SUCCESS: 'SET_PART_INFO_SUCCESS' 
}

export default ReaderActionTypes;