const ReaderOptionsActionTypes = {

  SET_APPEND_IF_SHORTER: 'SET_APPEND_IF_SHORTER', 
  SET_BREAK_IF_LONGER: 'SET_BREAK_IF_LONGER', 
  SET_MAX_APPEND: 'SET_MAX_APPEND', 
  SET_INITIAL_ACCELERATION_TIME_SECS: 'SET_INITIAL_ACCELERATION_TIME_SECS',
  SET_ADD_PER_MIN: 'SET_ADD_PER_MIN',
  SET_INITIAL_WPM: 'SET_INITIAL_WPM', 
  SET_INITIAL_CPM: 'SET_INITIAL_CPM' 

}

export default ReaderOptionsActionTypes;