const ReadingSessionActionTypes = {
  BEGIN_SESSION: 'BEGIN_SESSION', 
  END_SESSION: 'END_SESSION', 
  SET_OPTIONS_LOG: 'SET_OPTIONS_LOG', 
  SAVE_SESSION_START: 'SAVE_SESSION_START', 
  SAVE_SESSION_SUCCESS: 'SAVE_SESSION_SUCCESS', 
  SAVE_SESSION_FAILURE: 'SAVE_SESSION_FAILURE', 

  FETCH_DROPDOWN_SESSIONS_START: 'FETCH_DROPDOWN_SESSIONS_START', 
  FETCH_DROPDOWN_SESSIONS_SUCCESS: 'FETCH_DROPDOWN_SESSIONS_SUCCESS', 
  FETCH_DROPDOWN_SESSIONS_FAILURE: 'FETCH_DROPDOWN_SESSIONS_FAILURE', 

  FETCH_SESSION_GRAPH_START: 'FETCH_SESSION_GRAPH_START', 
  FETCH_SESSION_GRAPH_SUCCESS: 'FETCH_SESSION_GRAPH_SUCCESS', 
  FETCH_SESSION_GRAPH_FAILURE: 'FETCH_SESSION_GRAPH_FAILURE', 

  FETCH_READING_GRAPH_START: 'FETCH_READING_GRAPH_START', 
  FETCH_READING_GRAPH_SUCCESS: 'FETCH_READING_GRAPH_SUCCESS', 
  FETCH_READING_GRAPH_FAILURE: 'FETCH_READING_GRAPH_FAILURE', 

}

export default ReadingSessionActionTypes;