const ReadingSessionActionTypes = {
  BEGIN_SESSION: 'BEGIN_SESSION', 
  END_SESSION: 'END_SESSION', 
  SET_OPTIONS_LOG: 'SET_OPTIONS_LOG', 
  SAVE_SESSION_START: 'SAVE_SESSION_START', 
  SAVE_SESSION_SUCCESS: 'SAVE_SESSION_SUCCESS', 
  SAVE_SESSION_FAILURE: 'SAVE_SESSION_FAILURE', 

}

export default ReadingSessionActionTypes;