const ReadingActionTypes = {

  PROCESS_TEXT_START: 'PROCESS_TEXT_START',
  PROCESS_TEXT_SUCCESS: 'PROCESS_TEXT_SUCCESS',
  PROCESS_TEXT_FAILURE: 'PROCESS_TEXT_FAILURE',

  SET_TEXT: 'SET_TEXT',
  SET_READING_ID: 'SET_READING_ID',
  SET_TEXT_ARRAY: 'SET_TEXT_ARRAY',  
  SET_TEXT_ARRAY_ROW_INDEXES: 'SET_TEXT_ARRAY_ROW_INDEXES',  
  NULL_TEXT: 'NULL_TEXT',

  SET_TEXT_ENDED: 'SET_TEXT_ENDED'

}

export default ReadingActionTypes;