const ReadingActionTypes = {

  LOAD_TEXT_START: 'LOAD_TEXT_START',
  LOAD_TEXT_SUCCESS: 'LOAD_TEXT_SUCCESS',
  LOAD_TEXT_FAILURE: 'LOAD_TEXT_FAILURE',

  SET_TEXT: 'SET_TEXT',
  SET_TEXT_ARRAY: 'SET_TEXT_ARRAY',  
  NULL_TEXT: 'NULL_TEXT',

  SET_TEXT_ENDED: 'SET_TEXT_ENDED'

}

export default ReadingActionTypes;