const OfflineLibActionTypes = {

  ADD_READING: 'ADD_READING',
  SET_READINGS: 'SET_READINGS',
  SET_FILTERS: 'SET_FILTERS', 
  SET_READING_POSITIONS: 'SET_READING_POSITIONS',
  SET_READING_POSITION: 'SET_READING_POSITION'
  
}

export default OfflineLibActionTypes;