const OfflineLibActionTypes = {

  SET_OFFLINE_LIB: 'SET_OFFLINE_LIB',
  ADD_READING: 'ADD_READING',
  SET_READINGS: 'SET_READINGS',
  SET_FILTERS: 'SET_FILTERS', 
  SET_READING_POSITIONS: 'SET_READING_POSITIONS',
  SET_READING_POSITION: 'SET_READING_POSITION',
  ADD_TAGS: 'ADD_TAGS',
  UPDATE_READING_OFFLINE_START: 'UPDATE_READING_OFFLINE_START', 
  UPDATE_READING_OFFLINE_SUCCESS: 'UPDATE_READING_OFFLINE_SUCCESS', 
  REMOVE_READING: 'REMOVE_READING', 
  REMOVE_TAG: 'REMOVE_TAG', 

}

export default OfflineLibActionTypes;